- name: Install NodeJS  
  become: true
  apt:
    name: ['nodejs']
    state: latest

- name: Install npm
  become: true
  apt:
    name: ['npm']
    state: latest

- name: Install npm dependencies
  become: true
  command: 'npm install'
  args:
    chdir: '{{harv_path}}'

- name: Install Process Monitoring for Node JS
  become: true
  command: 'npm install pm2 -g'
  args:
    chdir: '{{harv_path}}'
