
## Uncomment to install python
# - hosts: back
#   vars_files:
#     - host_vars/cloud.yml
#   gather_facts: true
#   become: true
#   # pre_tasks:
#   #   - name: Update Ubuntu apt repo      
#   #     raw: apt-get update
#   #   - name: Install python 2
#   #     raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
#   #     register: output
#   #     changed_when: output.stdout != ""
#   #   - setup: # aka gather_facts

# # Uncomment to configure servers
# # Staging Inventory must be configured before that
# - hosts: web, db, back
#   become: true
#   vars_files:
#     - host_vars/cloud.yml
#   gather_facts: true
#   roles:    
#     - role: configure
    
## Uncomment to deploy harvesters
# - hosts: back   
#   vars_files:
#     - host_vars/cloud.yml
#   gather_facts: true
#   roles:    
#     - role: back-init
        

# Uncomment to deploy harvesters
- hosts: web
  vars_files:
    - host_vars/cloud.yml
  gather_facts: true
  roles:    
    - role: web-init