# Create volumes on cloud
- name: Create volumes
  os_volume:
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present  
  loop: '{{ volumes }}'
  register: os_vol

# Display list of volume IDs
- name: Create list of Volume IDs
  set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [item.id] }}'
  loop: '{{ os_vol.results }}'

- debug:
    msg: "Volumes {{ os_vol_ids }} has been created."