- name: Set auth key for Brendan
  authorized_key:
    user: ubuntu
    state: present
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCuyVb9MP5LzTuQm1qHrs4Z2KECQMHIaMkxu/tdMxCdNoOQUyMzjL53t2/OjST3CBaajrJ9tT7LFvnQyRyTjcyfRaaBZsn/L0sLLYQjwSOd044VIWd9oJ1Kv9U/Hd0L6jCKxR3TN2q0nqY256MTZOm8nrgJcWI/mmARfVTrwDOwTTmfYS6QCe0v4loLS3AFtEH/VmKK8LTG3of31PhYdpWquLSaaZmF2QBJp170SzhVcKWKTeWj2YO/xu3Gt2WxnvfHT4qL9TlcddC9ACzgdx39hxQeqspx+nx0qGhWCkdM3hB2DZn929EoOqoD3z8Nx2uD4ZTDP9eKO10eM/BNjEtuEkgPwsOdR5LDgrGelRJG2SnmBK5obKiVHlH3/he3JusSQAn51Z2o7kTFJTtAFdeRcdazx7U6uQiTF7ohR9dwdOHZTNdkNvH86Y/XcEEm2lSkPl92BJOeBtWL5kLQzNJf1tyeqllpINJ8D+miKF6M354o+W7cL4OwKkcQjnQBMnUR0ecNIVsYgsFXCMO3uWJwnK+5v631+CTeuiRZ/JNUhJ71daIAUFGBbyHImLQ6KWsO07MqOAsotV6FbqnsUkaQzqGHKilmlt9LThSq4nj7++dYInPea0oSdJu5BXp0fwj3WusPj3d/RW/MgULSHVVdEerTfFKKabJn9GJH8vNHfQ== brendan@LAPTOP-K9D2MLDC'


- name: Set auth key for Marko
  authorized_key:
    user: ubuntu
    state: present
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAyeUSAJhOqO5x1+ucSkl8WTsFz0pus9Fy4O+n3/Mkp2XQCzQ/cI9bDYs81Uwn3VVtEDRFt93VM4Qx8jA4/kDLwVzoMLL4nE7MNAzGU8C2ki+xoaX4XVkB+QAz8U/msxabs0zygz11yv3WjtZ8kpNoStm09pkh7yPOEg3gBpbRLEOYYtJ52ZPMDTS7M+5YB48qaMv14GM3pxh//kQ5cWwS8BHoiUOUoIzB75h1QfLYC+uxthf3xLPNj9bk9ob+CL2o4eFi4pn3fi+2OEnb4zQ1eSK3sdEHYDCEjCPg/SWYHLyIg/uANrt1g3O4sqb7GYhDykHhTbn95DGnl6xXBKO0Mw== rsa-key-20190413'


- name: Set auth key for Sathitsak
  authorized_key:
    user: ubuntu
    state: present
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCcY84l//ISLSRyk6mMV9y28sFea7gRX3HeiWYCd87fSCLlanhe4EKyWNLdN4hOOiIv5syeLNovS7vfT28LtKuCIPExJA6CWFjCyn9BAyXhqUitNC3vf7hG6XayKwO+Me3u8VCzRkK/gmYRJOTHn4tORMHon3cEq7yHFkKlIAVUTokpZ6jw8hmTZZ+jh1bOMxHSn0dqhqAUo6A71+5FKIRbSRRo/tyftaFEuk/FrBRSFuXPf1tR3KODyrLmBtJDYYJY6Lyp/q04ABZvp7MwarIy56/YuSY1NFffdOy0aefLKKOPA8xowhg7GYQmayzAHYYIT7YqB43PLssrvFESTrNJ Generated-by-Nova'


- name: Set auth key for Trung
  authorized_key:
    user: ubuntu
    state: present
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCk+wsWZO1BKQhHEacpted4epurhL6JT5emrqI6HG7ArjS6XKr7Je+mbB80kRvfSGjwZAzMqKBVSXXioc+J+2DoSh9M1dQJbqHnHZ2B9+HrvRNZnh0bAJQnyWBvdztgygLKYbWUFe3I0TrH+TCUFkK5EazZbaoIavzM5YkaXJbiS4/7xteg6amgip6SPfWk5ECavEnw4pvcJOsPV3AL9EUjMicfTZzusi/9jCsajYjn3y2IV4KXLZtZZYVC7iQAEduCT78/XjfO5X6hGnyNZ4d4Jjrz08ORwWoPU6RIY5qCGxezzf0qZuWy1wSa35Xgt1EXkuRSQxG+LhVGk3tTDZtL3TcLUijge/Z6dr0BHbpOIFAtqvZ6D/Cy1xBiGiUmRPP9D6qTAxqiMZVWh3o8Cs07+mlWHle2D5pqG4NXx+1zUkNxA312DLH7G5izP1nlSAOh0m4uG8pLQmsPOX9H89YdQRXRFzAmd7o2BB0zsl8OHWqLHgOYFgScf3O2+x+BZfzlUniSxc/O2fcpQDovbmhZUqsieMXUjetVy/86VgQ84+6MlGK2q9DZxVKunoxXpoQoHzcxgA40IlTeCd1SM9R5NILAINaKDMs61WYYwQqfiSqGybqImY09ncLLilNK2xwH1ih3fQJAYhDFTbTlu6SDvzgOQKNvf135UNDWdNyubw== sathitsak@laptop'