- name: Add HTTP Proxy
  lineinfile:
    path: /etc/environment
    insertafter: EOF
    line: 'http_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    create: yes


- name: Add HTTPS Proxy
  lineinfile:
    path: /etc/environment
    insertafter: EOF
    line: 'https_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    create: yes

- name: Add FTP Proxy
  lineinfile:
    path: /etc/environment
    insertafter: EOF
    line: 'ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    create: yes


- name: Add Localhost No Proxy Setting
  lineinfile:
    path: /etc/environment
    insertafter: EOF
    line: 'no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu'
    create: yes