
# Save DB server ip for further configurations
- set_fact: db_ip='{{hostvars['db'].ansible_ssh_host}}'

- name: Show Database server IP
  debug:
    var: db_ip

- name: Set Connection to DB
  become: true
  lineinfile:
    path: '{{pres_path}}/.env'
    regexp: '^COUD_DB_HOST'
    line: 'COUD_DB_HOST={{ db_ip }}'

- name: Setup PM2 to start on boot  
  become: true
  command: 'env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu'

- name: Starting API Gateway
  command: 'pm2 start server.js --watch --name "api" -- "api"'
  args:
    chdir: '{{pres_path}}'

# Save DB server ip for further configurations
- set_fact: web_ip='{{ansible_default_ipv4.address}}'

- name: Connect Web App to API
  become: true
  lineinfile:
    path: '{{pres_path}}/client/src/api.js'
    regexp: '^var apiBaseUrl'
    line: 'var apiBaseUrl = "http://{{ web_ip }}:5000"'

- name: Starting Web App
  command: 'pm2 start node_modules/react-scripts/bin/react-scripts.js --watch --name web -- start'
  args:
    chdir: '{{pres_path}}/client'
    
- name: Freeze API Gateway and Webapp as part of service boot    
  command: 'pm2 save'

- name: Show Web Server IP
  debug:
    var: web_ip