version: '3.5'

services:

  sample-app:
    container_name: sample-app
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true